version: '3'

services:
  caddy:
    image: artmadar/micro-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  front-end:
    image: artmadar/front-end:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  broker-service:
    image: artmadar/broker-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: artmadar/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
  authenticate-service:
    image: artmadar/authentication-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    image: artmadar/logger-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  mail-service:
    image: artmadar/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: "mailhog"
      MAIL_PORT: 1025
      MAIL_ENCRYPT: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM_NAME: "Alexander Gronsky"
      MAIL_FROM_MAIL: "alex.artmadar@gmail.com"

  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    deploy:
      mode: global

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    deploy:
      mode: global

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: loggerService
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: 'postgres:14.2-alpine'
    ports:
      - "2345:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config:

